services:

  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - home_jenkins:/home/jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
  agent:
    container_name: agent
    image: jenkins/inbound-agent:3355.v388858a_47b_33-6-jdk25
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=agent
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
      - JENKINS_SECRET=7043af164ac3dee8fb35cf92f5a77c0be0c462b194576f1161522be0f8622a08 
    volumes:
      - home_jenkins:/home/jenkins
    networks:
      - jenkins

networks:
  jenkins:
volumes:
  home_jenkins:
